spring.application.name=usuarios
server.port=8080
server.address=0.0.0.0

spring.datasource.url=${DB_URL:jdbc:postgresql://postgres:5432/usuariosdb?currentSchema=usuarios_schema}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=usuarios_schema
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=true

instance.tag=${INSTANCE_TAG:app-local}
